### testing api call


#### users


### Get user
GET http://localhost:8000/api/v1/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNoYW5rckBnbWFpbC5jb20iLCJpYXQiOjE3MjkwNDQzMDUsImV4cCI6MTcyOTA0NDM2NX0.Ie48irMFQNoCgLFMP7WCO2IbT-GOrn8C4AFHHtFq7BY


### Post user
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
    "name":"Shankar",
    "email":"shankr@gmail.com",
    "password":"123"
    
}
### Login User

POST http://localhost:8000/api/v1/users/login
Content-Type: application/json

{
    "email":"shankr@gmail.com",
    "password":"123"
    
}



### Transactions

### POST new transaction
POST http://localhost:8000/api/v1/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNoYW5rckBnbWFpbC5jb20iLCJpYXQiOjE3MzAwNzE3OTYsImV4cCI6MTczMDE1ODE5Nn0.4xyU0KuSoYmlAt7tF66dYQBw4uDBdFLsNoz6cFm6_ns

{
    "type":"income",
    "title":"Wages",
    "amount":"55",
    "tdate":"04-23-2023"

}


### Get tranasction for logged in user

GET  http://localhost:8000/api/v1/transactions
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNoYW5rckBnbWFpbC5jb20iLCJpYXQiOjE3MzAxMTM1NzEsImV4cCI6MTczMDE5OTk3MX0.Dg83WFjlVYs08yVgIa-o8TGeXci6gb8QaPTM1mTPguU


### Delete Transaction for logged in user

DELETE http://localhost:8000/api/v1/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNoYW5rckBnbWFpbC5jb20iLCJpYXQiOjE3MzA2MDM1NDMsImV4cCI6MTczMDY4OTk0M30.z19UC6VB-nuc5gMKGtQpK9DpnTblHKxjDZ3pe6r4S5Y

["67241b8f1e422a2e8e97029d"]